import FormatService from "src/services/FormatService";

export default {
  getReportColumns: () => [
    {name: 'id', required: true, align: 'center', label: 'Código', field: 'id'},
    {
      name: 'timestamp',
      required: true,
      label: 'Timestamp',
      align: 'left',
      field: 'timestamp',
      sortable: true,
      // format: val => FormatService.setDateFormatParams(val)
    },
    {
      name: 'local',
      required: true,
      align: 'left',
      label: 'local',
      field: 'local',
      sortable: false,
    },
    {
      name: 'management_type',
      required: true,
      label: 'Tipo de arqueo',
      align: 'left',
      field: 'management_type',
      sortable: false,
    },
    {
      name: 'sales_day',
      required: true,
      label: 'Jornada de venta',
      align: 'left',
      field: 'sales_day',
      sortable: false,
    },
    {
      name: 'operator_open',
      required: true,
      label: 'Operador apertura',
      align: 'left',
      field: 'operator_open',
      sortable: false,
    },
    {
      name: 'operator_close',
      required: true,
      label: 'Operador cierre',
      align: 'left',
      field: 'operator_open',
      sortable: false,
    },
    {
      name: 'current_cash_fund',
      label: 'Fondo actual',
      align: 'right',
      field: 'current_cash_fund',
      sortable: false,
    },
    {
      name: 'differences',
      align: 'right',
      field: 'differences',
      label: 'Diferencias',
      sortable: false,
    },
    {
      name: 'sales_mix',
      align: 'right',
      field: 'sales_mix',
      label: 'Ventas mixtas',
      sortable: false,
    },
    {
      name: 'sales_usd',
      align: 'right',
      field: 'sales_usd',
      label: 'Ventas USD',
      sortable: false,
    },
    {
      name: 'sales_card',
      align: 'right',
      field: 'sales_card',
      label: 'Ventas Tarjeta',
      sortable: false,
    },
    {
      name: 'sales_total',
      align: 'right',
      field: 'sales_total',
      label: 'Ventas Total',
      sortable: false,
    },
    {
      name: 'actions',
      label: 'Acciones',
      align: 'center',
    },
  ],
  getFakeData: () => [
    {
      id: '001',
      timestamp: '2024-11-01 09:30',
      local: 'Sucursal 1',
      management_type: 'Diario',
      sales_day: '2024-11-01',
      operator_open: 'Juan Pérez',
      operator_close: 'Ana Gómez',
      current_cash_fund: 1500.00,
      differences: 10.00,
      sales_mix: 500.00,
      sales_usd: 200.00,
      sales_card: 800.00,
      sales_total: 1500.00,
      actions: ''
    },
    {
      id: '002',
      timestamp: '2024-11-01 14:00',
      local: 'Sucursal 2',
      management_type: 'Diario',
      sales_day: '2024-11-01',
      operator_open: 'Luis García',
      operator_close: 'Marta López',
      current_cash_fund: 1200.00,
      differences: 5.00,
      sales_mix: 400.00,
      sales_usd: 100.00,
      sales_card: 700.00,
      sales_total: 1200.00,
      actions: ''
    },
    {
      id: '003',
      timestamp: '2024-11-02 09:30',
      local: 'Sucursal 3',
      management_type: 'Diario',
      sales_day: '2024-11-02',
      operator_open: 'Carlos Díaz',
      operator_close: 'Lucía Fernández',
      current_cash_fund: 1300.00,
      differences: -20.00,
      sales_mix: 600.00,
      sales_usd: 300.00,
      sales_card: 400.00,
      sales_total: 1300.00,
      actions: ''
    },
    {
      id: '004',
      timestamp: '2024-11-02 14:00',
      local: 'Sucursal 4',
      management_type: 'Diario',
      sales_day: '2024-11-02',
      operator_open: 'Fernando Ortega',
      operator_close: 'María Sánchez',
      current_cash_fund: 1600.00,
      differences: 0.00,
      sales_mix: 800.00,
      sales_usd: 200.00,
      sales_card: 600.00,
      sales_total: 1600.00,
      actions: ''
    },
    {
      id: '005',
      timestamp: '2024-11-03 09:30',
      local: 'Sucursal 1',
      management_type: 'Semanal',
      sales_day: '2024-11-03',
      operator_open: 'David Morales',
      operator_close: 'Laura Romero',
      current_cash_fund: 1400.00,
      differences: 15.00,
      sales_mix: 450.00,
      sales_usd: 250.00,
      sales_card: 700.00,
      sales_total: 1400.00,
      actions: ''
    },
    {
      id: '006',
      timestamp: '2024-11-03 14:00',
      local: 'Sucursal 2',
      management_type: 'Semanal',
      sales_day: '2024-11-03',
      operator_open: 'Pedro Blanco',
      operator_close: 'Sofía Díaz',
      current_cash_fund: 1250.00,
      differences: -10.00,
      sales_mix: 550.00,
      sales_usd: 100.00,
      sales_card: 600.00,
      sales_total: 1250.00,
      actions: ''
    },
    {
      id: '007',
      timestamp: '2024-11-04 09:30',
      local: 'Sucursal 3',
      management_type: 'Diario',
      sales_day: '2024-11-04',
      operator_open: 'Miguel Castillo',
      operator_close: 'Sara Flores',
      current_cash_fund: 1700.00,
      differences: 20.00,
      sales_mix: 750.00,
      sales_usd: 150.00,
      sales_card: 800.00,
      sales_total: 1700.00,
      actions: ''
    },
    {
      id: '008',
      timestamp: '2024-11-04 14:00',
      local: 'Sucursal 4',
      management_type: 'Diario',
      sales_day: '2024-11-04',
      operator_open: 'Andrés Pérez',
      operator_close: 'Elena Ruiz',
      current_cash_fund: 1800.00,
      differences: -5.00,
      sales_mix: 900.00,
      sales_usd: 100.00,
      sales_card: 800.00,
      sales_total: 1800.00,
      actions: ''
    }
  ]
}
