export default {
  getReportColumns: () => [
    {name: 'id', required: true, align: 'center', label: 'Código', field: 'id'},
    {
      name: 'timestamp',
      required: true,
      label: 'Timestamp',
      align: 'left',
      field: 'timestamp',
      sortable: true,
    },
    {
      name: 'local',
      required: true,
      align: 'left',
      label: 'local',
      field: 'local',
      sortable: false,
    },
    {
      name: 'management_type',
      required: true,
      label: 'Tipo de arqueo',
      align: 'left',
      field: 'management_type',
      sortable: false,
    },
    {
      name: 'sales_day',
      required: true,
      label: 'Jornada de venta',
      align: 'left',
      field: 'sales_day',
      sortable: false,
    },
    {
      name: 'operator_open',
      required: true,
      label: 'Operador apertura',
      align: 'left',
      field: 'operator_open',
      sortable: false,
    },
    {
      name: 'operator_close',
      required: true,
      label: 'Operador cierre',
      align: 'left',
      field: 'operator_open',
      sortable: false,
    },
    {
      name: 'current_cash_fund',
      label: 'Fondo actual',
      align: 'right',
      field: 'current_cash_fund',
      sortable: false,
    },
    {
      name: 'differences',
      align: 'right',
      field: 'differences',
      label: 'Diferencias',
      sortable: false,
    },
    {
      name: 'sales_mix',
      align: 'right',
      field: 'sales_mix',
      label: 'Ventas mixtas',
      sortable: false,
    },
    {
      name: 'sales_usd',
      align: 'right',
      field: 'sales_usd',
      label: 'Ventas USD',
      sortable: false,
    },
    {
      name: 'sales_card',
      align: 'right',
      field: 'sales_card',
      label: 'Ventas Tarjeta',
      sortable: false,
    },
    {
      name: 'sales_total',
      align: 'right',
      field: 'sales_total',
      label: 'Ventas Total',
      sortable: false,
    },
    {
      name: 'actions',
      label: 'Acciones',
      align: 'center',
    },
  ],
  getFakeData: () => [
    {
      id: '001',
      timestamp: '2024-11-01 09:30',
      local: 'Sucursal 1',
      management_type: 'Diario',
      sales_day: '2024-11-01',
      operator_open: 'Juan Pérez',
      operator_close: 'Ana Gómez',
      current_cash_fund: 1500.00,
      differences: 10.00,
      sales_mix: 500.00,
      sales_usd: 200.00,
      sales_card: 800.00,
      sales_total: 1500.00,
      actions: ''
    }
  ]
}
